from datetime import datetime
import os

def generate_report(cpu, ram, disk, health_score):
    report_name = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    
    try:
        with open("history.csv", "r") as f:
            history_data = f.readlines()
    except:
        history_data = []

    with open(report_name, "w") as file:
        file.write("=" * 60 + "\n")
        file.write("🦅 NEXUS AUTONOMOUS OS OPTIMIZATION REPORT\n")
        file.write("=" * 60 + "\n\n")

        file.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")

        file.write("📊 CURRENT SYSTEM METRICS\n")
        file.write("-" * 60 + "\n")
        file.write(f"CPU Usage:              {cpu}%\n")
        file.write(f"RAM Usage:              {ram}%\n")
        file.write(f"Disk Usage:             {disk}%\n")
        file.write(f"Overall Health Score:   {health_score}/100\n\n")

        file.write("📈 HEALTH INTERPRETATION\n")
        file.write("-" * 60 + "\n")
        if health_score >= 90:
            file.write("Status: EXCELLENT - System is operating optimally\n")
        elif health_score >= 75:
            file.write("Status: GOOD - Minor optimizations recommended\n")
        elif health_score >= 60:
            file.write("Status: WARNING - Maintenance needed soon\n")
        else:
            file.write("Status: CRITICAL - Immediate action required\n")

        file.write("\n🔄 OPTIMIZATION RECOMMENDATIONS\n")
        file.write("-" * 60 + "\n")
        
        if cpu > 80:
            file.write("• CPU: Close resource-intensive applications\n")
        if ram > 80:
            file.write("• RAM: Clear browser cache and unused applications\n")
        if disk > 85:
            file.write("• DISK: Run cleanup of temporary and junk files\n")
        
        if cpu <= 80 and ram <= 80 and disk <= 85:
            file.write("• System is well-optimized. Continue regular maintenance.\n")

        file.write("\n📝 HISTORICAL PERFORMANCE\n")
        file.write("-" * 60 + "\n")
        file.write(f"Total history entries: {len(history_data)}\n")
        
        if history_data:
            file.write(f"First entry: {history_data[0].strip()}\n")
            file.write(f"Latest entry: {history_data[-1].strip()}\n")

        file.write("\n" + "=" * 60 + "\n")
        file.write("Report generated by Nexus Autonomous OS Agent\n")
        file.write("=" * 60 + "\n")

    return report_name